### PR TITLE
I am your father

### PR DESCRIPTION
**Pull request by peter-clemenko**
Also a few fixes to yaml files

### CODE REVIEW

**Comment by frikky** [comment]
Do you mind adding some simple docs for this one, explaining what it is and when to use it? I checked out SentimentIntensityAnalyzer, but couldn't immediately understand how I'd use it. 

Thanks :D

**Comment by peter-clemenko** [comment]
How do you want the docs?

**Comment by frikky** [comment]
> How do you want the docs?

Here's some examples: https://github.com/frikky/Shuffle-apps/tree/master/Docs
We'll further relate these to the apps themselves, and publish them as part of app usage when exploring apps in the future.

**Comment by jasontant** [comment]
> We'll further relate these to the apps themselves, and publish them as part of app usage when exploring apps in the future. Just write a reference to it here somewhere and we'll deal with the whole linking thing later. No need to overcomplicate it right now.

I've been thinking about whether it would make sense to add a MY_APP/VERSION/doc directory with markdown.  That way it would be in place with and updated along with the app.  At some future point, that could lend itself to a UI interface to pull up the docs for a specific app.  Thoughts?

**Comment by frikky** [comment]
> > We'll further relate these to the apps themselves, and publish them as part of app usage when exploring apps in the future. Just write a reference to it here somewhere and we'll deal with the whole linking thing later. No need to overcomplicate it right now.
> 
> I've been thinking about whether it would make sense to add a MY_APP/VERSION/doc directory with markdown. That way it would be in place with and updated along with the app. At some future point, that could lend itself to a UI feature to pull up the docs for a specific app. Thoughts?

Yep this works as well, and you're right that it's probably a better structure. Do you think we should do something like this for OpenAPI as well? Put it under APPNAME/VERSION/doc? It would probably be beneficial long-term, however we don't follow versioning for those yet, and we'll for sure get more of those than python.

**Comment by jasontant** [comment]
> Do you think we should do something like this for OpenAPI as well? Put it under APPNAME/VERSION/doc? 

Without a doubt, yes.  My mindset is to keep the docs close to the code.  Reduce the number of repos people have to track, manage, and maintain.  I imagine that will help reduce (but never eliminate) lag between the docs and the code to a certain extent.

**Comment by peter-clemenko** [comment]
I agree with the directory change, however I would modify one thing and make sure the docs are localized

**Comment by peter-clemenko** [comment]
Check it out now, see if this is good

**Comment by frikky** [comment]
Looks good now! Let's migrate all the apps soonish to follow the same structure :)

**Pull request merged**
