### PR TITLE
Add attachments support to owa

### PR DESCRIPTION
**Pull request by dadokkio**
Add support for uploading attachment to shuffle after get_mails and add attachments in send_mail

### CODE REVIEW

**Comment by frikky** [comment]
Nice, well done! 

I think a standard workflow for this would be really useful at this point to help other people out :fire:

**Comment by dadokkio** [comment]
We are aligned probably :D

I've only a little problem, If I have multiple attachments from multiple emails the variable became something like:

`$read_mails.#.attachments_uids.#`

But if I pass this to a input (eg. as file for filedata param in extract_archive) it says that is not valid because list of list. 
How to manage this properly?

**Comment by frikky** [comment]
@dadokkio List of list shouldn't really be a problem, but I think it's a general issue with multiple files. I'll have to check this properly!

**Comment by dadokkio** [comment]
At the moment I'm using with

$read_mails.#.attachments_uids.#0

And is working fine.. but just picking one attachment for each email

**Comment by frikky** [comment]
Ye, #0 and # work completely differently in the background, even if there's only one element. I'll get this working ASAP :+1:

**Pull request merged**
