### PR TITLE
✨ Add function to map value from a ditionary

### PR DESCRIPTION
**Pull request by pemontto**

### CODE REVIEW

**Comment by pemontto** [comment]
Example docker container output:
```
[INFO] Running normal execution

Got mapping {
  "Informational": 1,
  "Low": 2,
  "Medium": 3,
  "High": 4
}
Mapping High to 4

[INFO] Returned from execution!
[INFO] POST NEWRES RESULT!
```

**Comment by frikky** [comment]
oooh, nice. This kind of does the same as the "translate value", but multiple of them. Will definitely add a "multi-value" thing for this in the future so that you can add and remove values in the GUI instead of JSON

**Comment by pemontto** [comment]
I think the translate function is more like a "replace", or even "sanitise" function. It finds multiple different values and replaces them with a single one.

**Comment by frikky** [comment]
Yep, you're right. Btw, as you're so good at using Emoji's with your plugins and such: How about we add a way to have emoji's/icons next to actions?

We'll probably end up adding something like Mitre Att&ck or Re&ct tags to actions as well in the future.

image

**Comment by pemontto** [comment]
Yes excellent idea, it can reduce cognitive load and scanning time. I haven't tried but I assume emojis can already be used by adding them to the action text?
If you wanted a more structured definition, maybe a new YAML key for `icon` and do something to [HomeAssistant](https://www.home-assistant.io/docs/configuration/customizing-devices/#icon) and use a pre-loaded icon pack like [Material Design Icons](https://materialdesignicons.com/).
So for SMS - `mdi:message-processing` message-processing (1)
Email `mdi:at` or `mdi:email-send` at email-send

**Comment by pemontto** [comment]
An icon pack also has the benefit of consistency and availability cross platform.

**Pull request merged**
