### PR TITLE
Added GitGuardian app

### PR DESCRIPTION
**Pull request by dhaval055**
Sorry for the delay.

### CODE REVIEW

**Comment by frikky** [comment]
This looks good - is it possible to add listing of incidents and such though? E.g. this right here

image

Is there a hidden API?

**Comment by dhaval055** [comment]
> This looks good - is it possible to add listing of incidents and such though? E.g. this right here
> 
> 
> 
> Is there a hidden API?

As of now its not possible to pull incidents via API. But [here](https://roadmap.gitguardian.com/c/35-api-handle-incidents-and-historical-scans-programmatically) it says they're working on it.

**Comment by dhaval055** [comment]
> > This looks good - is it possible to add listing of incidents and such though? E.g. this right here
> > Is there a hidden API?
> 
> As of now its not possible to pull incidents via API. But [here](https://roadmap.gitguardian.com/c/35-api-handle-incidents-and-historical-scans-programmatically) it says they're working on it.

It can be done using [custom webhook ](https://docs.gitguardian.com/internal-repositories-monitoring/notifications/custom_webhook)though.

**Comment by frikky** [comment]
> > > This looks good - is it possible to add listing of incidents and such though? E.g. this right here
> > > Is there a hidden API?
> > 
> > 
> > As of now its not possible to pull incidents via API. But [here](https://roadmap.gitguardian.com/c/35-api-handle-incidents-and-historical-scans-programmatically) it says they're working on it.
> 
> It can be done using [custom webhook ](https://docs.gitguardian.com/internal-repositories-monitoring/notifications/custom_webhook)though.

Understood - let's keep it on the backburner for now, and get back to it if they release an "official" API

**Pull request merged**
