### PR TITLE
Add Base64 encode/decode to Shuffle Tools

### PR DESCRIPTION
**Pull request by arnydo**
Add base64 encode/decode actions to Shuffle Tools.

image

### CODE REVIEW

**Comment by frikky** [comment]
Sweet - love it! Any way we can merge these into a single function using options? 

:100:

**Comment by arnydo** [comment]
Great idea! Yeah, I think that would be a better route.

**Comment by arnydo** [comment]
Good call on combining the actions.

Sorry for the delay in getting it done.

image

**Comment by frikky** [comment]
Nice - the encode/decode thing is really neat. I'm thinking this will turn into a sort of encode/decode thing in general long-term. 

PS: Feel free to add your name somewhere in there for each of the actions. We'll make a way to automate this based on pullrequests in the future, but any reference to originator is always good I think. Maybe we should also add an encode() and decode() function to the frontend itself to potentially make it faster.

Anyways - this is cool

**Pull request merged**
